Zeitpunkt: 2023-09-13 18:31:58,465
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 70, in nominal_phrase_agreement_analysis
    morpho_results = demorphy.get_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 114, in get_raw_np_morphology
    np_data = self.get_read_in_np_file()  # Holen der geladenen NP-Daten
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/demorphy_manager.py", line 93, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/nps_1091_0000269.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/nps_1091_0000269.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 100
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-09-13 18:43:10,990
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 70, in nominal_phrase_agreement_analysis
    morpho_results = demorphy.get_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 114, in get_raw_np_morphology
    np_data = self.get_read_in_np_file()  # Holen der geladenen NP-Daten
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/demorphy_manager.py", line 93, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/nps_1091_0000269.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/extracted_nominal_phrases/nps_1091_0000269.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 100
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

