Zeitpunkt: 2023-08-26 18:57:30,346
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 122, in nominal_congruency_check
    np_is_proper_or_common = self.common_proper_nominal_phrase(vocabulary_np)
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 38, in common_proper_nominal_phrase
    common = detector.check_common_phrases()
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 32, in check_common_phrases
    common_phrases = self.__load_in_ner_data().get("common_phrases")
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 26, in __load_in_ner_data
    common_proper = open(self.common_proper, mode="r", encoding="utf-8").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/data/NER/common_names.txt'

Nachricht: [Errno 2] No such file or directory: 'app_resources/data/NER/common_names.txt'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:57:30,346
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 122, in nominal_congruency_check
    np_is_proper_or_common = self.common_proper_nominal_phrase(vocabulary_np)
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 38, in common_proper_nominal_phrase
    common = detector.check_common_phrases()
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 32, in check_common_phrases
    common_phrases = self.__load_in_ner_data().get("common_phrases")
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 26, in __load_in_ner_data
    common_proper = open(self.common_proper, mode="r", encoding="utf-8").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/data/NER/common_names.txt'

Nachricht: [Errno 2] No such file or directory: 'app_resources/data/NER/common_names.txt'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:57:30,346
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 122, in nominal_congruency_check
    np_is_proper_or_common = self.common_proper_nominal_phrase(vocabulary_np)
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 38, in common_proper_nominal_phrase
    common = detector.check_common_phrases()
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 32, in check_common_phrases
    common_phrases = self.__load_in_ner_data().get("common_phrases")
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 26, in __load_in_ner_data
    common_proper = open(self.common_proper, mode="r", encoding="utf-8").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/data/NER/common_names.txt'

Nachricht: [Errno 2] No such file or directory: 'app_resources/data/NER/common_names.txt'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:57:30,645
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 1_die Arbeit konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 271, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:57:30,646
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 2_Wiviel konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 271, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:57:30,646
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 3_Reche Pflichen konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 271, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:58:28,232
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 122, in nominal_congruency_check
    np_is_proper_or_common = self.common_proper_nominal_phrase(vocabulary_np)
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 38, in common_proper_nominal_phrase
    common = detector.check_common_phrases()
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 32, in check_common_phrases
    common_phrases = self.__load_in_ner_data().get("common_phrases")
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 26, in __load_in_ner_data
    common_proper = open(self.common_proper, mode="r", encoding="utf-8").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/data/CER/common_names.txt'

Nachricht: [Errno 2] No such file or directory: 'app_resources/data/CER/common_names.txt'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:58:28,232
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 122, in nominal_congruency_check
    np_is_proper_or_common = self.common_proper_nominal_phrase(vocabulary_np)
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 38, in common_proper_nominal_phrase
    common = detector.check_common_phrases()
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 32, in check_common_phrases
    common_phrases = self.__load_in_ner_data().get("common_phrases")
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 26, in __load_in_ner_data
    common_proper = open(self.common_proper, mode="r", encoding="utf-8").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/data/CER/common_names.txt'

Nachricht: [Errno 2] No such file or directory: 'app_resources/data/CER/common_names.txt'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:58:28,232
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 122, in nominal_congruency_check
    np_is_proper_or_common = self.common_proper_nominal_phrase(vocabulary_np)
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 38, in common_proper_nominal_phrase
    common = detector.check_common_phrases()
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 32, in check_common_phrases
    common_phrases = self.__load_in_ner_data().get("common_phrases")
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 26, in __load_in_ner_data
    common_proper = open(self.common_proper, mode="r", encoding="utf-8").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/data/CER/common_names.txt'

Nachricht: [Errno 2] No such file or directory: 'app_resources/data/CER/common_names.txt'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:58:28,532
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 1_die Arbeit konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 271, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:58:28,532
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 2_Wiviel konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 271, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 18:58:28,532
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 3_Reche Pflichen konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 271, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 20:14:58,823
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 121, in nominal_congruency_check
    np_is_proper_or_common = detector.check_common_phrase_or_proper(
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 44, in check_common_phrase_or_proper
    raise CusEm.CerPhraseorProperArgument
kongru.api_general.universal.constants.error_messages.custom_error_messages.CustomErrorMessages.CerPhraseorProperArgument: Entweder 'phrases' oder 'proper_common' als Argument angeben.

Nachricht: Entweder 'phrases' oder 'proper_common' als Argument angeben.
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 20:14:59,119
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 1_Wiesbaden Stadt konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 273, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 20:21:10,359
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: ___
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 124, in nominal_congruency_check
    np_is_phrase = detector.check_common_phrase_or_proper(
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/analyzers/common_entity_recognition.py", line 44, in check_common_phrase_or_proper
    raise CusEm.CerPhraseorProperArgument
kongru.api_general.universal.constants.error_messages.custom_error_messages.CustomErrorMessages.CerPhraseorProperArgument: Entweder 'phrases' oder 'proper_common' als Argument angeben.

Nachricht: Entweder 'phrases' oder 'proper_common' als Argument angeben.
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-26 20:21:10,685
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: 1_Wiesbaden Stadt konnte nicht gespeichert werden.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_nlp/congruential_analysis/congruency/np_congruency.py", line 276, in save_congruency_results
    csv_writer.writerow(result)
_csv.Error: iterable expected, not NoneType

Nachricht: iterable expected, not NoneType
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 60
Dateipfad: /Users/christopherchandler/repo/Python/De_NP_Kongru/kongru/api_general/universal/funcs/basic_logger.py

