Zeitpunkt: 2023-08-27 11:01:37,709
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 52, in run_analysis
    morpho_results = demorphy.find_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 56, in find_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/data_parsers/demorphy_parser.py", line 80, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/christopherchandler/repo/Python/De_NP_Kongru/user/outgoing/np/np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: '/Users/christopherchandler/repo/Python/De_NP_Kongru/user/outgoing/np/np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 62
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-27 11:03:28,734
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 52, in run_analysis
    morpho_results = demorphy.find_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 56, in find_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/data_parsers/demorphy_parser.py", line 79, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/christopherchandler/repo/Python/De_NP_Kongru/user/outgoing/np/np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: '/Users/christopherchandler/repo/Python/De_NP_Kongru/user/outgoing/np/np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 62
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-27 11:07:57,692
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 52, in run_analysis
    morpho_results = demorphy.find_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 56, in find_raw_np_morphology
    np_data = self.get_read_in_np_file()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/data_parsers/demorphy_parser.py", line 79, in get_read_in_np_file
    with open(file_name, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'GeneralPaths.TEST_NP_FILE_CSV'

Nachricht: [Errno 2] No such file or directory: 'GeneralPaths.TEST_NP_FILE_CSV'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 62
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-27 11:08:02,856
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 52, in run_analysis
    morpho_results = demorphy.find_raw_np_morphology()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/analyzers/demorphy_analyzer.py", line 57, in find_raw_np_morphology
    morph_dict = self.get_read_in_demorphy_dict()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/data_parsers/demorphy_parser.py", line 55, in get_read_in_demorphy_dict
    with open(Gp.DB_DEMORTHY_PKL.value, "rb") as pickle_file:
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/data/morpho_dict/demorphy_dict.pkl'

Nachricht: [Errno 2] No such file or directory: 'app_resources/data/morpho_dict/demorphy_dict.pkl'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 62
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

