Zeitpunkt: 2023-08-29 06:41:27,089
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 62, in run_analysis
    np_congruency.save_congruency_results()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/congruency/nominal_phrase_congruency.py", line 496, in save_congruency_results
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:42:03,211
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 62, in run_analysis
    np_congruency.save_congruency_results()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/congruency/nominal_phrase_congruency.py", line 496, in save_congruency_results
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:42:25,306
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Bei der Analyse ist etwas schief gelaufen.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/app_congruential_analysis.py", line 62, in run_analysis
    np_congruency.save_congruency_results()
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_nlp/congruential_analysis/congruency/nominal_phrase_congruency.py", line 496, in save_congruency_results
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'

Nachricht: [Errno 2] No such file or directory: 'user/outgoing/np_analysis_results/2023_08_29_np_test_1023_0001416.csv'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:44:15,886
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 98
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 06:51:13,924
Loggername: root
LogLevel: INFO
Nachricht: Ergebnisse wurden gespeichert
Modul: basic_logger
Funktion: log_info
Linie: 98
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:06:09,605
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 44, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:06:13,138
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 44, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:07:32,253
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 44, in look_up_data_entry
    if merlin_corpus.get("conll"):
AttributeError: 'NoneType' object has no attribute 'get'

Nachricht: 'NoneType' object has no attribute 'get'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:08:28,896
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 45, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:08:38,363
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 45, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:08:50,155
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 45, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:09:55,491
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 46, in look_up_data_entry
    merlin_corpus.pop("conll")
AttributeError: 'NoneType' object has no attribute 'pop'

Nachricht: 'NoneType' object has no attribute 'pop'
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:12:18,018
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:12:21,073
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:00,035
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:23,982
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:23,982
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/app_data_managers.py", line 42, in look_up_data_entry
    for entry in merlin_corpus:
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:13:51,139
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

Zeitpunkt: 2023-08-29 10:14:18,155
Loggername: root
LogLevel: ERROR
Benutzerdefiniert: Die Text-ID, die eingegeben wurde, ist nicht gültig.
Traceback: Traceback (most recent call last):
  File "/Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/database_managers/managers/merlin_manager.py", line 305, in extract_entry_by_id
    for entry, col in zip(entry_row, entry_columns):
TypeError: 'NoneType' object is not iterable

Nachricht: 'NoneType' object is not iterable
Modul: basic_logger
Funktion: catch_and_log_error
Linie: 86
Dateipfad: /Users/christopherchandler/repo/Python/computerlinguistik/de_np_kongru/kongru/api_general/universal/funcs/basic_logger.py

